#!/usr/bin/env bash
# ────────────────────────────────────────────────────────────────────────────
# Zylos Docker Entrypoint
#
# 1. Validates required environment variables
# 2. Writes ~/zylos/.env from environment (or uses mounted file)
# 3. Initialises zylos workspace (first-run only)
# 4. Starts PM2 services
# 5. Starts Claude Code inside a persistent tmux session
# 6. Keeps container alive via PM2 --no-daemon
# ────────────────────────────────────────────────────────────────────────────
set -euo pipefail

ZYLOS_DIR="${HOME}/zylos"
ENV_FILE="${ZYLOS_DIR}/.env"

# ── Colour helpers ────────────────────────────────────────────────────────────
info()  { echo -e "\033[0;36m[zylos]\033[0m $*"; }
warn()  { echo -e "\033[1;33m[zylos]\033[0m $*"; }
error() { echo -e "\033[0;31m[zylos]\033[0m $*" >&2; }

info "Starting Zylos ($(zylos --version 2>/dev/null || echo 'dev'))..."

# ── Write .env if not already mounted ────────────────────────────────────────
if [ ! -f "${ENV_FILE}" ]; then
  info "Generating ${ENV_FILE} from environment variables..."
  cat > "${ENV_FILE}" <<EOF
# Auto-generated by Docker entrypoint — edit and restart container to change

TZ=${TZ:-UTC}
CLAUDE_BYPASS_PERMISSIONS=${CLAUDE_BYPASS_PERMISSIONS:-true}

# Auth: provide ONE of the following
${ANTHROPIC_API_KEY:+ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}}
${CLAUDE_CODE_OAUTH_TOKEN:+CLAUDE_CODE_OAUTH_TOKEN=${CLAUDE_CODE_OAUTH_TOKEN}}

# Channels
${TELEGRAM_BOT_TOKEN:+TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}}
${LARK_APP_ID:+LARK_APP_ID=${LARK_APP_ID}}
${LARK_APP_SECRET:+LARK_APP_SECRET=${LARK_APP_SECRET}}

# Web console
${ZYLOS_WEB_PASSWORD:+ZYLOS_WEB_PASSWORD=${ZYLOS_WEB_PASSWORD}}

# System PATH hint (helps PM2 find claude and node)
SYSTEM_PATH=${PATH}
EOF
  info ".env written."
else
  info "Using mounted .env at ${ENV_FILE}."
fi

# ── Validate auth ─────────────────────────────────────────────────────────────
if [ -z "${ANTHROPIC_API_KEY:-}" ] && [ -z "${CLAUDE_CODE_OAUTH_TOKEN:-}" ]; then
  # Check .env as fallback
  if ! grep -qE '^(ANTHROPIC_API_KEY|CLAUDE_CODE_OAUTH_TOKEN)=' "${ENV_FILE}" 2>/dev/null; then
    error "No auth configured. Set ANTHROPIC_API_KEY or CLAUDE_CODE_OAUTH_TOKEN."
    exit 1
  fi
fi

# ── One-time workspace initialisation ─────────────────────────────────────────
INIT_MARKER="${ZYLOS_DIR}/.docker-init-done"
if [ ! -f "${INIT_MARKER}" ]; then
  info "First run — initialising zylos workspace..."
  zylos init \
    --yes \
    --no-interactive \
    ${ZYLOS_TIMEZONE:+--timezone "${ZYLOS_TIMEZONE}"} \
    || true   # init may prompt; best-effort
  touch "${INIT_MARKER}"
  info "Workspace initialised."
fi

# ── Start PM2 services ────────────────────────────────────────────────────────
info "Starting PM2 services..."
pm2 start "${ZYLOS_DIR}/pm2/ecosystem.config.cjs" --no-daemon &
PM2_PID=$!

# Give PM2 a moment to spin up core services
sleep 3

# ── Start Claude Code in tmux ─────────────────────────────────────────────────
info "Starting Claude Code session (tmux: claude-main)..."

# Kill any stale session
tmux kill-session -t claude-main 2>/dev/null || true

# Build claude command
CLAUDE_ARGS=""
if [ "${CLAUDE_BYPASS_PERMISSIONS:-true}" = "true" ]; then
  CLAUDE_ARGS="--dangerously-skip-permissions"
fi

tmux new-session -d -s claude-main -x 220 -y 50 \
  "cd ${HOME} && source ${ENV_FILE} 2>/dev/null; exec claude ${CLAUDE_ARGS}"

info "Claude Code session started."

# ── Keep container alive ──────────────────────────────────────────────────────
info "All services started. Monitoring PM2..."
wait "${PM2_PID}"
